from django.shortcuts import render
def login_page(request): return render(request,'frontend/login.html')
def dashboard(request): return render(request,'frontend/dashboard.html',{'active_page':'dashboard'})
def students(request): return render(request,'frontend/students.html',{'active_page':'students'})
def student_detail(request,student_id): return render(request,'frontend/student_detail.html',{'active_page':'students','student_pk':student_id})
def courses(request): return render(request,'frontend/courses.html',{'active_page':'courses'})
def enrollments(request): return render(request,'frontend/enrollments.html',{'active_page':'enrollments'})
def activity_log(request): return render(request,'frontend/activity_log.html',{'active_page':'activity'})
def portal(request): return render(request,'frontend/portal.html',{'active_page':'portal'})
