# Generated by Django 5.2.17 on 2026-08-29 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learning_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='core_course_course__2a9d7b_idx',
            old_name='core_course_course_c_6f2f7e_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='core_studen_last_na_d07597_idx',
            old_name='core_studen_last_na_6b5e4d_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='core_studen_email_26bdb0_idx',
            old_name='core_studen_email_6e0f4a_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+999999999' (9-15 digits).", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
